### ISSUE TITLE
PyHEP 2022 "proceedings"

### ISSUE THREAD

**Issue by eduardo-rodrigues** [alexander-held/agc-binder#5]
Hello @alexander-held, I see that you already have a DOI for your PyHEP 2022 talk. Can you then "attach it" in Zenodo to the pyhep2022 community so as to be part of the "proceedings"? I will get a ping to curate and accept.

Also nicer if you update the title of the Zenodo page to the actual talk title ;-).

Many thanks.

**Comment by alexander-held** [comment]
Hi Eduardo, I've sent a request to include this contribution to the PyHEP 2022 community and updated the entry with title and abstract.

**Comment by eduardo-rodrigues** [comment]
Hi Alex. Thanks, got it.

Note that I also got another email
```
A new upload requests to be added to your community (PyHEP 2021 Workshop):


Record Title: alexander-held/PyHEP-2021-cabinetry: v1.1
Record Description: Talk as presented at PyHEP 2021: https://indico.cern.ch/event/1019958/contributions/4421868/]. Binder links now use the Zenodo archive, and an evaluated version of the notebook has been added.

You can accept or reject this record in your community curation page:
https://zenodo.org/communities/pyhep2021/curate/
```
that must be a mistake since from last year and I believe I got everything from last year at https://zenodo.org/communities/pyhep2021. Let me know if not and I will act. Otherwise I will reject the duplicate.

Thanks again,

**Comment by alexander-held** [comment]
Hi @eduardo-rodrigues, thanks for pointing out this duplication. I had a closer look now and https://zenodo.org/record/6798532 is already in the community, while yesterday I came across https://zenodo.org/record/5102837 and saw that it was not in there. I do not know why this is split up, but just realized that I do not have edit permissions for the former, so perhaps this was uploaded centrally by the PyHEP team? Either way, it is fine with me to just leave this all as-is, feel free to reject this new request then.

**Comment by eduardo-rodrigues** [comment]
OK, now I compared both and one if for the PDF whereas the other one is for the repository, meaning the code. In those cases I actually do 2 Zenodo entries, to be comprehensive. Both entries are now in the pyhep2021 community. All sorted :-).
